/* Instant project files from a prompt. Used even if Ada's model is offline. */
(function (w) {
  "use strict";

  function esc(s) {
    return String(s || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function titleOf(prompt) {
    var t = String(prompt || "").replace(/\s+/g, " ").trim();
    t = t.replace(/^create:\s*/i, "").replace(/^create\s+/i, "");
    if (t.length > 70) t = t.slice(0, 67) + "…";
    return t || "My project";
  }

  function kindOf(prompt) {
    var q = String(prompt || "").toLowerCase();
    if (/snake|pong|tetris|\bgame\b/.test(q)) return "game";
    if (/todo|to-do|task list|checklist/.test(q)) return "todo";
    if (/quiz|trivia|questions/.test(q)) return "quiz";
    if (/timer|pomodoro|stopwatch/.test(q)) return "timer";
    if (/score|cricket|scoreboard/.test(q)) return "score";
    if (/photo|portfolio|gallery|photographer/.test(q)) return "gallery";
    if (/baker|cafe|shop|store|menu|restaurant|food/.test(q)) return "shop";
    if (/dash|stats|analytics/.test(q)) return "dash";
    return "landing";
  }

  function readme(title, language) {
    return "# " + title + "\n\nGenerated on Semicolon.\n\nLanguage: " + language +
      "\n\nHTML/CSS/JS: press Run / Preview or open index.html.\n" +
      "Python/C/Java/SQL: copy the files and run them on your computer. " +
      "This site does not execute those languages on the server.\n";
  }

  function cssBase() {
    return ":root{--bg:#0b1020;--card:#161b33;--ink:#f8fafc;--muted:#c4b5fd;--accent:#6366f1;--rose:#e11d48}\n" +
      "*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:#0b1020;color:var(--ink);min-height:100vh}\n" +
      "header,main,footer{max-width:56rem;margin:0 auto;padding:1.25rem 1.1rem}\n" +
      "header{background:linear-gradient(135deg,#312e81,#4f46e5 55%,#e11d48);border-radius:0 0 24px 24px}\n" +
      "h1{margin:.2rem 0 .4rem;font-size:clamp(1.6rem,4vw,2.5rem)}p.lead{opacity:.92}\n" +
      ".grid{display:grid;gap:1rem;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr))}\n" +
      ".card{background:var(--card);border:1px solid #312e81;border-radius:16px;padding:1rem}\n" +
      "button,input,select,textarea{font:inherit;padding:.65rem .8rem;border-radius:12px;border:1px solid #4338ca}\n" +
      "button{background:var(--accent);color:#fff;border:0;cursor:pointer}\n" +
      "input,textarea,select{background:#0b1020;color:inherit;width:100%}\n" +
      "nav a{color:#fff;margin-right:1rem;text-decoration:none;font-weight:600}\n" +
      "footer{opacity:.7;font-size:.85rem}\n";
  }

  function page(title, extraHead, bodyInner, jsFile) {
    return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n" +
      "  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" +
      "  <title>" + esc(title) + "</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n" + extraHead +
      "</head>\n<body>\n" + bodyInner + "\n  <script src=\"" + (jsFile || "script.js") + "\"></script>\n</body>\n</html>\n";
  }

  function webProject(prompt, language, output) {
    var title = titleOf(prompt);
    var kind = kindOf(prompt);
    var html = "";
    var js = "";
    var css = cssBase();

    if (kind === "gallery") {
      html = page(title, "",
        "  <header><nav><a href=\"#work\">Work</a><a href=\"#about\">About</a></nav>" +
        "<p>Photography</p><h1>" + esc(title) + "</h1>" +
        "<p class=\"lead\">A simple gallery you can extend. Click a frame.</p></header>" +
        "  <main id=\"work\" class=\"grid\"></main>" +
        "  <footer id=\"about\"><p>Generated by Ada on Semicolon.</p></footer>");
      js = "var shots=['Golden hour','Studio portrait','Street rain','Wide landscape','Detail','Night city'];\n" +
        "var main=document.querySelector('main');\n" +
        "shots.forEach(function(name,i){\n" +
        "  var art=document.createElement('article');\n" +
        "  art.className='card';\n" +
        "  art.innerHTML='<div style=\"height:9rem;border-radius:12px;background:linear-gradient('+(120+i*20)+'deg,#4f46e5,#e11d48)\"></div><h2>'+name+'</h2><p>Frame '+(i+1)+'</p>';\n" +
        "  art.onclick=function(){alert(name);};\n" +
        "  main.appendChild(art);\n" +
        "});\n";
    } else if (kind === "shop") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1><p class=\"lead\">Today's menu. Add to bag.</p></header>" +
        "  <main><div class=\"grid\" id=\"menu\"></div><aside class=\"card\" style=\"margin-top:1rem\"><h2>Bag</h2><ul id=\"bag\"></ul><p id=\"total\"></p></aside></main>" +
        "  <footer><p>Semicolon Code Generator</p></footer>");
      js = "var items=[{n:'Sourdough',p:4},{n:'Croissant',p:3},{n:'Coffee',p:2.5},{n:'Cake slice',p:5}];\n" +
        "var bag=[];\n" +
        "function draw(){\n" +
        "  document.getElementById('menu').innerHTML=items.map(function(it,i){return '<article class=\"card\"><h2>'+it.n+'</h2><p>£'+it.p.toFixed(2)+'</p><button data-i=\"'+i+'\">Add</button></article>';}).join('');\n" +
        "  document.getElementById('bag').innerHTML=bag.map(function(it){return '<li>'+it.n+'</li>';}).join('')||'<li>Empty</li>';\n" +
        "  var t=bag.reduce(function(s,it){return s+it.p;},0);\n" +
        "  document.getElementById('total').textContent='Total £'+t.toFixed(2);\n" +
        "}\n" +
        "document.getElementById('menu').addEventListener('click',function(e){\n" +
        "  var b=e.target.closest('button'); if(!b) return; bag.push(items[Number(b.getAttribute('data-i'))]); draw();\n" +
        "});\ndraw();\n";
    } else if (kind === "todo") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1><p class=\"lead\">Tasks stay in this browser.</p></header>" +
        "  <main class=\"card\"><form id=\"f\"><input id=\"t\" placeholder=\"New task\"><button>Add</button></form><ul id=\"list\"></ul></main>");
      css += "form{display:flex;gap:.5rem}#list{list-style:none;padding:0}#list li{display:flex;justify-content:space-between;padding:.6rem 0;border-bottom:1px solid #312e81}\n";
      js = "var key='todo-'+" + JSON.stringify(title) + ";\n" +
        "var items=JSON.parse(localStorage.getItem(key)||'[]');\n" +
        "function draw(){var ul=document.getElementById('list');ul.innerHTML='';items.forEach(function(x,i){var li=document.createElement('li');li.innerHTML='<span></span><button type=\"button\">done</button>';li.querySelector('span').textContent=x;li.querySelector('button').onclick=function(){items.splice(i,1);localStorage.setItem(key,JSON.stringify(items));draw();};ul.appendChild(li);});}\n" +
        "document.getElementById('f').onsubmit=function(e){e.preventDefault();var v=document.getElementById('t').value.trim();if(!v)return;items.push(v);localStorage.setItem(key,JSON.stringify(items));document.getElementById('t').value='';draw();};\ndraw();\n";
    } else if (kind === "quiz") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1><p class=\"lead\" id=\"q\"></p></header>" +
        "  <main class=\"card\" id=\"opts\"></main><p id=\"score\" style=\"text-align:center\"></p>");
      js = "var qs=[{q:'How many planets in the Solar System (classic 8)?',a:['7','8','9'],c:1},{q:'Closest star to Earth?',a:['Sirius','The Sun','Alpha Centauri'],c:1},{q:'H2O is',a:['Salt','Water','Oxygen'],c:1}];\n" +
        "var i=0,ok=0;\nfunction show(){if(i>=qs.length){document.getElementById('q').textContent='Done';document.getElementById('opts').innerHTML='';document.getElementById('score').textContent='Score '+ok+' / '+qs.length;return;}\n" +
        "var x=qs[i];document.getElementById('q').textContent=x.q;document.getElementById('opts').innerHTML=x.a.map(function(t,n){return '<p><button data-n=\"'+n+'\">'+t+'</button></p>';}).join('');}\n" +
        "document.getElementById('opts').onclick=function(e){var b=e.target.closest('button');if(!b)return;if(Number(b.getAttribute('data-n'))===qs[i].c)ok++;i++;show();};\nshow();\n";
    } else if (kind === "timer") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1></header>" +
        "  <main class=\"card\" style=\"text-align:center\"><p id=\"clock\" style=\"font-size:3rem\">25:00</p>" +
        "<button id=\"start\">Start</button> <button id=\"reset\">Reset</button></main>");
      js = "var left=25*60,t=null;\nfunction fmt(){var m=Math.floor(left/60),s=left%60;document.getElementById('clock').textContent=m+':'+String(s).padStart(2,'0');}\n" +
        "document.getElementById('start').onclick=function(){if(t)return;t=setInterval(function(){if(left<=0){clearInterval(t);t=null;return;}left--;fmt();},1000);};\n" +
        "document.getElementById('reset').onclick=function(){clearInterval(t);t=null;left=25*60;fmt();};\nfmt();\n";
    } else if (kind === "score") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1></header>" +
        "  <main class=\"grid\"><article class=\"card\"><h2 id=\"a\">0</h2><button id=\"plusA\">Team A +1</button></article>" +
        "<article class=\"card\"><h2 id=\"b\">0</h2><button id=\"plusB\">Team B +1</button></article></main>");
      js = "var a=0,b=0;\nfunction draw(){document.getElementById('a').textContent=a;document.getElementById('b').textContent=b;}\n" +
        "document.getElementById('plusA').onclick=function(){a++;draw();};\n" +
        "document.getElementById('plusB').onclick=function(){b++;draw();};\n";
    } else if (kind === "game") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1><p class=\"lead\">Arrows move. Catch the square.</p></header>" +
        "  <main><canvas id=\"c\" width=\"480\" height=\"320\" style=\"width:100%;background:#111;border-radius:16px\"></canvas><p id=\"s\"></p></main>");
      js = "var c=document.getElementById('c'),x=c.getContext('2d'),px=40,py=40,gx=200,gy=120,sc=0;\n" +
        "var keys={};\naddEventListener('keydown',function(e){keys[e.key]=true;});\naddEventListener('keyup',function(e){keys[e.key]=false;});\n" +
        "function tick(){if(keys.ArrowRight)px+=4;if(keys.ArrowLeft)px-=4;if(keys.ArrowUp)py-=4;if(keys.ArrowDown)py+=4;\n" +
        "px=Math.max(0,Math.min(460,px));py=Math.max(0,Math.min(300,py));\n" +
        "if(Math.abs(px-gx)<20&&Math.abs(py-gy)<20){sc++;gx=Math.random()*440;gy=Math.random()*280;}\n" +
        "x.fillStyle='#0b1020';x.fillRect(0,0,480,320);x.fillStyle='#6366f1';x.fillRect(px,py,20,20);x.fillStyle='#e11d48';x.fillRect(gx,gy,20,20);\n" +
        "document.getElementById('s').textContent='Score '+sc;\nrequestAnimationFrame(tick);}tick();\n";
    } else if (kind === "dash") {
      html = page(title, "",
        "  <header><h1>" + esc(title) + "</h1></header>" +
        "  <main class=\"grid\" id=\"cards\"></main>");
      js = "var rows=[{k:'Visitors',v:1280},{k:'Sign-ups',v:42},{k:'Revenue',v:'£310'}];\n" +
        "document.getElementById('cards').innerHTML=rows.map(function(r){return '<article class=\"card\"><p>'+r.k+'</p><h2>'+r.v+'</h2></article>';}).join('');\n";
    } else {
      var words = title.split(/\s+/).slice(0, 6);
      html = page(title, "",
        "  <header><nav><a href=\"#about\">About</a><a href=\"#work\">Work</a></nav>" +
        "<h1>" + esc(title) + "</h1><p class=\"lead\">Built from your prompt on Semicolon.</p>" +
        "<p><button id=\"cta\">Get started</button></p></header>" +
        "  <main id=\"about\" class=\"grid\"></main>" +
        "  <section id=\"work\" class=\"card\" style=\"max-width:56rem;margin:1rem auto\"><h2>Notes</h2><ul id=\"notes\"></ul></section>" +
        "  <footer><p>Learn. Code. Build.</p></footer>");
      js = "var bits=" + JSON.stringify(words) + ";\n" +
        "document.querySelector('#about').innerHTML=bits.map(function(w){return '<article class=\"card\"><h2>'+w+'</h2><p>Section generated from your words.</p></article>';}).join('');\n" +
        "document.getElementById('cta').onclick=function(){document.getElementById('work').scrollIntoView({behavior:'smooth'});};\n" +
        "document.getElementById('notes').innerHTML='<li>'+" + JSON.stringify(title) + "+'</li>';\n";
    }

    if (String(output).toLowerCase() === "single" || String(language).toLowerCase() === "html" && String(output).toLowerCase() === "single") {
      var bundled = html.replace('<link rel="stylesheet" href="style.css">', "<style>\n" + css + "</style>")
        .replace('<script src="script.js"></script>', "<script>\n" + js + "</script>");
      return [
        { path: "index.html", content: bundled },
        { path: "README.md", content: readme(title, language) }
      ];
    }
    return [
      { path: "index.html", content: html },
      { path: "style.css", content: css },
      { path: "script.js", content: js },
      { path: "README.md", content: readme(title, language) }
    ];
  }

  function build(prompt, language, framework, difficulty, output) {
    var lang = String(language || "HTML").toLowerCase();
    var title = titleOf(prompt);
    if (lang === "python") {
      return [
        { path: "main.py", content:
          '"""' + title + '"""\n\n' +
          "def main():\n" +
          "    topic = " + JSON.stringify(title) + "\n" +
          "    print('Semicolon')\n" +
          "    print(topic)\n" +
          "    words = [w for w in topic.replace(',', ' ').split() if w]\n" +
          "    for i, w in enumerate(words, 1):\n" +
          "        print(f'{i}. {w}')\n" +
          "    return words\n\n" +
          "if __name__ == '__main__':\n" +
          "    main()\n" },
        { path: "README.md", content: readme(title, language) + "\nRun: python3 main.py\n" }
      ];
    }
    if (lang === "c") {
      var lit = title.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
      return [
        { path: "main.c", content: "#include <stdio.h>\nint main(void) {\n  printf(\"Semicolon\\n" + lit + "\\n\");\n  return 0;\n}\n" },
        { path: "README.md", content: readme(title, language) + "\nCompile: gcc main.c -o app && ./app\n" }
      ];
    }
    if (lang === "c++") {
      var lit2 = title.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
      return [
        { path: "main.cpp", content: "#include <iostream>\nint main() {\n  std::cout << \"Semicolon\\n" + lit2 + "\\n\";\n  return 0;\n}\n" },
        { path: "README.md", content: readme(title, language) + "\nCompile: g++ main.cpp -o app && ./app\n" }
      ];
    }
    if (lang === "java") {
      var lit3 = title.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
      return [
        { path: "Main.java", content: "public class Main {\n  public static void main(String[] args) {\n    System.out.println(\"Semicolon\");\n    System.out.println(\"" + lit3 + "\");\n  }\n}\n" },
        { path: "README.md", content: readme(title, language) + "\nRun: javac Main.java && java Main\n" }
      ];
    }
    if (lang === "sql") {
      var safe = title.replace(/'/g, "''");
      return [
        { path: "query.sql", content: "-- " + title + "\nCREATE TABLE items (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL\n);\nINSERT INTO items (name) VALUES ('" + safe + "');\nSELECT * FROM items;\n" },
        { path: "README.md", content: readme(title, language) }
      ];
    }
    if (lang === "javascript" && String(output).toLowerCase() === "single") {
      var web = webProject(prompt, language, "project");
      var jsFile = web.filter(function (f) { return f.path === "script.js"; })[0];
      return [jsFile || { path: "script.js", content: "console.log(" + JSON.stringify(title) + ");\n" }, { path: "README.md", content: readme(title, language) }];
    }
    return webProject(prompt, language, output);
  }

  w.SemiGen = { build: build, titleOf: titleOf, kindOf: kindOf };
})(window);
